[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "background-job-management-service"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "alembic",
    "fastapi",
    "pydantic",
    "sqlalchemy",
    "uvicorn",
]

[project.optional-dependencies]
test = [
    "httpx",
    "pytest",
]

[tool.setuptools.packages.find]
include = ["app*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
