"""create short urls table

Revision ID: c15cd1899a3b
Revises: 
Create Date: 2026-07-27 16:23:24.886942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15cd1899a3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_code', sa.String(length=32), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redirect_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('redirect_count >= 0', name='ck_short_urls_redirect_count_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code', name='uq_short_urls_short_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_urls')
    # ### end Alembic commands ###
